project:
  type: website
  output-dir: ../pb_public
  preview:
    port: 4400
execute:
  freeze: true
website:
  title: "Commonmeta"
  favicon: favicon.ico
  navbar:
    background: light
    logo: "/images/icon.png"
    logo-alt: "Commonmeta"
    right:
      - icon: github
        href: https://github.com/commonmeta/commonmeta
  sidebar:
    contents:
      - index.qmd
      - challenges.qmd
      - implementations.qmd
      - use-cases.qmd
      - schema.qmd
  page-footer:
    left: "Copyright &copy;2023-2024 Commonmeta."
    right:
      - icon: envelope
        href: mailto:info@front-matter.io
      - icon: mastodon 
        href: https://wisskomm.social/@rogue_scholar

format:
  html:
    theme:
      light: [flatly, theme.scss]
      dark: [darkly, theme.scss]
    page-layout: article
    toc: true
    toc-location: right
